# Generated by Django 3.2.9 on 2021-11-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211125_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='use_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата использования'),
        ),
    ]
