# Generated by Django 3.2.9 on 2021-11-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_card_use_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
