# Generated by Django 3.2.9 on 2021-11-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211125_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.card', verbose_name='Карта'),
        ),
    ]
