# Generated by Django 3.2.9 on 2021-11-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_item_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_active',
            field=models.CharField(default='Активна', max_length=255, verbose_name='Статус'),
        ),
    ]
