# Generated by Django 3.2.9 on 2021-12-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_card_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='card',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main.card', verbose_name='Карта'),
            preserve_default=False,
        ),
    ]
