# Generated by Django 3.2.9 on 2021-12-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_item_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_sum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Сумма'),
        ),
    ]
